# Generated by Django 5.2.6 on 2025-09-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_diary_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='diary',
        ),
        migrations.DeleteModel(
            name='Diary',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
