# Generated by Django 5.2.6 on 2025-09-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_fa',
            field=models.BooleanField(default=True),
        ),
    ]
