# Generated by Django 5.2.6 on 2025-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
