# Generated by Django 5.2.6 on 2025-10-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary_todo', '0002_alter_todo_end_time_alter_todo_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('completed', 'Completed')], default='not_started'),
        ),
    ]
